In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import mnist

# Numpy Expand Dimension 

In [14]:
array = ([1, 2], [3, 4])
a_np_arr = np.array(array)

print(a_np_arr)
print(a_np_arr.shape)

b_minus_1 = np.expand_dims(a_np_arr, axis=-1)
print(b_minus_1)
print(b_minus_1.shape)

b_plus = np.expand_dims(a_np_arr, axis=1)
print(b_plus)
print(b_plus.shape)

b_zero = np.expand_dims(a_np_arr, axis=0)
print(b_zero)
print(b_zero.shape)

a = [5, 6, 7]
b = np.expand_dims(a, axis=-1)
print(b)



[[1 2]
 [3 4]]
(2, 2)
[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)
[[[1 2]]

 [[3 4]]]
(2, 1, 2)
[[[1 2]
  [3 4]]]
(1, 2, 2)
[[5]
 [6]
 [7]]


# MNIST Classification

Keras, CNN Layers and Models assignment

In [2]:
keras = tf.keras
layers = keras.layers
models = keras.models

In [3]:
model = models.Sequential([
    layers.Input(shape=(32, 32, 1)),
    layers.Conv2D(6, (5, 5), activation='relu'),
    layers.AveragePooling2D((2, 2)),
    layers.Conv2D(15, (5, 5), activation='relu'),
    layers.AveragePooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(12, activation='relu'),
    layers.Dense(8, activation='relu'),
    layers.Dense(10, activation='softmax')
])